version: '3.4'

services:
  apinest:
    image: apinest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      APP_PORT: 3000
      DB_TYPE: mysql
      DB_HOST: 'host.docker.internal'
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: admin
      DB_NAME: apinest
    ports:
      - 3000:3000
  # mydb:
  #   image: mysql:8.0.32
  #   container_name: lfowks_mysql
  #   restart: always
  #   command: [
  #     '--default-authentication-plugin=mysql_native_password',
  #     '--character-set-server=utf8mb4',
  #     '--collation-server=utf8mb4_unicode_ci',
  #   ]
  #   environment:
  #     MYSQL_DATABASE: apinest
  #     MYSQL_ROOT_PASSWORD: admin
  #   ports:
  #     - 3307:3306

